const STORAGE_KEY = 'savs-party-september-2025-09';

const scavengerItems = [
    { clue: "Recently spent 3 months in Brussels (ask about their PowerPoint)", answer: "" },
    { clue: "Once rallied with Roger Federer", answer: "" },
    { clue: "Knows the dance to Gnarly", answer: "" },
    { clue: "Been to The Sphere 6 times", answer: "" },
    { clue: "Secret degree in fashion design", answer: "" },
    { clue: "Went to culinary school", answer: "" },
    { clue: "Doesn't know how to juggle", answer: "" },
    { clue: "Helped Arden Cho evolve her Magikarp into a Gyarados", answer: "" },
    { clue: "Spent a month in Thailand at a fight camp as a sidequest when on leave from work", answer: "" },
    { clue: "Went to the last ever Brooklyn Mirage concert in 2024", answer: "" },
    { clue: "Made 3 trips to Asia in the first half of this year", answer: "" },
    { clue: "Went to elementary school with Sav", answer: "" },
    { clue: "Married to the person who went to elementary school with Sav", answer: "" },
    { clue: "Brother stole their teeth in the womb", answer: "" },
    { clue: "Went to Citi Field 5 times this summer", answer: "" },
    { clue: "Can whistle like a bird", answer: "" },
    { clue: "Has never chewed gum", answer: "" },
    { clue: "Tried to come up with a fun fact for 30 minutes but has been faced with the unpleasant truth that they are not very interesting", answer: "" },
    { clue: "Very good at card magic", answer: "" },
    { clue: "Was an extra in Marvels Black Panther movie", answer: "" },
    { clue: "Thinks watermelon seeds add at least 20% enjoyment to the watermelon", answer: "" },
    { clue: "Doesn't like discos", answer: "" },
    { clue: "Runs a semi-pro soccer club", answer: "" },
    { clue: "Allergic to peaches", answer: "" },
    { clue: "Flying to Portugal tonight", answer: "" },
    { clue: "Tall(ish)", answer: "" },
    { clue: "Arms are fucked up from dislocations", answer: "" },
    { clue: "Pretty good at Venetian boat racing", answer: "" },
    { clue: "Justice is their middle name", answer: "" },
    { clue: "Is playing a show at Bowery Electric on October 11 (catch em all)", answer: "" },
    { clue: "Just hiked to Machu Picchu", answer: "" },
    { clue: "Made their own shampoo & conditioner for 6 years", answer: "" },
    { clue: "Won 2 pie eating contests", answer: "" },
    { clue: "Wind sign", answer: "" },
    { clue: "Second degree black belt", answer: "" },
    { clue: "Middle finger is the same length as index", answer: "" },
];

initScavenger(scavengerItems, STORAGE_KEY);
